[project]
name = "magicboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "albumentations",
    "customtkinter",
    "ipykernel",
    "jupyter",
    "matplotlib",
    "mediapipe",
    "numpy",
    "opencv-python",
    "openni",
    "pandas",
    "pillow",
    "pygame",
    "pyttsx3",
    "pyyaml",
    "scikit-image",
    "seaborn",
    "spacy",
    "sentence-transformers",
    "SpeechRecognition",
    "pyaudio",
    "torch",
    "torchvision",
    "tqdm",
    "ultralytics",
    "ollama>=0.6.1",
    "python-dotenv>=1.2.2",
]
